# Generated by Django 4.2.17 on 2025-01-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Время опубликования')),
                ('time_to_read', models.CharField(max_length=50, verbose_name='Среднее время прочтения')),
                ('text', models.TextField(verbose_name='Содержание')),
                ('cover', models.ImageField(upload_to='cover/%Y/%m/%d/', verbose_name='Обложка книги')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
            ],
        ),
    ]
